@echo off
echo 🚀 Arret et suppression des conteneurs et volumes existants...
docker compose down -v

echo 🔥 Reconstruction et demarrage des conteneurs (db + backend)...
docker compose up --build -d db backend

echo 📦 Reinstallation des dependances...
docker compose exec backend npm install

echo 🛠️ Generation du client Prisma...
docker compose exec backend npm run db:generate

echo 🗄️ Migration de la base de donnees...
docker compose exec backend npm run db:migrate:dev

echo 🌱 Seeding de la base de donnees...
docker compose exec backend npm run db:seed

echo 🚀 Lancement complet avec Adminer...
docker compose up
