Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3NTE0NDUzOTksImV4cCI6MTc1MTUzMTc5OX0.ArOew4ryc0oRjkdVZXr93cTVEMoQPxnpRQlXL93sm-k

### User registration
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email": "member@new.fr",
    "password": "testtest",
    "role": "member",
    "firstname": "test",
    "lastname": "test",
    "user_type_id": 1
}

### GET ALL TYPES
GET http://localhost:3001/locations